package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2024-JUL-03  09:51:55 AM
 */
public class AllInOneFile extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(54);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: WelcomePrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "WelcomePrompt", "WelcomePrompt.wav", ""); 

		// phrase: DepartureTimePrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "DepartureTimePrompt", "DepartureTimePrompt.wav", ""); 

		// phrase: ExistingBookingStatusPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "ExistingBookingStatusPrompt", "ExistingBookingStatusPrompt.wav", ""); 

		// phrase: ExistingUserMenuPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "ExistingUserMenuPrompt", "ExistingUserMenuPrompt.wav", ""); 

		// phrase: LastTripPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "LastTripPrompt", "LastTripPrompt.wav", ""); 

		// phrase: MainMenuPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "MainMenuPrompt", "MainMenuPrompt.wav", ""); 

		// phrase: NewUserPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "NewUserPrompt", "NewUserPrompt.wav", ""); 

		// phrase: NoInputPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "NoInputPrompt", "NoInputPrompt.wav", ""); 

		// phrase: NoMatchPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "NoMatchPrompt", "NoMatchPrompt.wav", ""); 

		// phrase: ThanksPrompt
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "ThanksPrompt", "ThanksPrompt.wav", ""); 

		// phrase: TransferPrompot
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "TransferPrompot", "TransferPrompot.wav", ""); 

		// phrase: TestPrompot
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "TestPrompot", "TestPrompot.wav", ""); 

		// phrase: checkstatus
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "checkstatus", "checkstatus.wav", ""); 

		// phrase: bookstatus
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "bookstatus", "bookstatus.wav", ""); 

		// phrase: Maximumlimits
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "Maximumlimits", "Maximumlimits.wav", ""); 

		// phrase: tripdetails
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "tripdetails", "tripdetails.wav", ""); 

		// phrase: pnrnumber
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "pnrnumber", "pnrnumber.wav", ""); 

		// phrase: departuredate
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "departuredate", "departuredate.wav", ""); 

		// phrase: bookingdate
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "bookingdate", "bookingdate.wav", ""); 

		// phrase: confirmed
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "confirmed", "confirmed.wav", ""); 

		// phrase: waiting
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "waiting", "waiting.wav", ""); 

		// phrase: year
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "year", "year.wav", ""); 

		// phrase: month
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "month", "month.wav", ""); 

		// phrase: date
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "date", "date.wav", ""); 

		// phrase: hours
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "hours", "hours.wav", ""); 

		// phrase: minutes
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "minutes", "minutes.wav", ""); 

		// phrase: seconds
		com.avaya.sce.runtime.Phraseset.addExternalPhrase(PHRASE_MAP, "english.phraseset.AllInOneFile.urlbase", "seconds", "seconds.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2024-JUL-31  05:04:29 PM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(AllInOneFile.PHRASE_MAP, phraseName));
	}
}
