package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2024-JUL-04  03:29:52 PM
 */
public class BookId extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for BookId.
    */
    public BookId() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("voice");
        setBuiltin(true);
        setBuiltinMode("grammar");
        setType("digits");
        setOptions("minlength=8;maxlength=10");
		//}}END:CLASS:CONSTRUCTOR
    }

}

